blank_issues_enabled: true
contact_links:
  - name: Documentação
    url: https://github.com/lregio/conclave-mr#readme
    about: Antes de abrir uma issue, dê uma olhada no README e em CONTRIBUTING.md.
